# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    
jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.2
        
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.2.0
        
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3.1
      
      - name: Navigate to root folder
        run: cd $GITHUB_WORKSPACE
        
      - name: Restore NuGet Packages
        run: nuget restore
        
      - name: Build Solution
        run: msbuild /p:platform="Any CPU" /p:configuration=Release
        
      - name: Run Unit tests
        run: dotnet test --configuration Release --filter Importers.UnitTests
        
      - name: Run Integration tests
        run: dotnet test --configuration Release --filter Importers.IntegrationTests
      
      - name: Navigate to startup project
        run: cd PresentationLayer
        
      - name: Publish applications
        run: msbuild /t:publish /p:configuration=Release /p:PublishDir=publish/
        
      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: EvaluationManagerSetup
          path: PresentationLayer/publish/
